In [26]:
import torch
import numpy as np

In [8]:
v = torch.tensor([1,2,3,4,5,6])
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [3]:
print(v.dtype)

torch.int64


In [12]:
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [15]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f)

tensor([1., 2., 3., 4., 5., 6.])


In [16]:
print(f.dtype)

torch.float32


In [18]:
print(f.size())

torch.Size([6])


In [21]:
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [22]:
v.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [24]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [37]:
a = np.array([1,2,3,4,5])
tensor_conv = torch.from_numpy(a)
print(tensor_conv)
print(tensor_conv.type())

tensor([1, 2, 3, 4, 5], dtype=torch.int32)
torch.IntTensor


In [39]:
numpy_conv = tensor_conv.numpy()
print(numpy_conv)

[1 2 3 4 5]
