In [1]:
import torch

In [5]:
one_d = torch.arange(0,9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
two_d = one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
two_d.dim()

2

In [9]:
one_d.dim()

1

In [15]:
two_d[1, 2]

tensor(5)

In [23]:
x = torch.arange(18).view(3,2,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])